spring:
  application:
    name: stayease
  config:
    import: optional:.env.properties
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      ssl:
        enabled: true
      timeout: 60000
    jdbc:
      repositories:
        enabled: false
  mail:
    host: smtp.mailersend.net
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
pending:
  cleanup:
    cron: 0 0 */12 * * ?
#okta:
#  oauth2:
#    issuer: https://strwbry.us.auth0.com/
#    client-id: NjOIipXd8PoJpN0dRGv0kPIn1anXqlhX
#    client-secret: ${OKTA_CLIENT_SECRET}
#    redirect-uri: ${OKTA_REDIRECT_URI}